### ISSUE TITLE
Unable to check videos, playlists or channels

### ISSUE THREAD

**Issue by SuperScoops** [axcore/tartube#175]
Using v2.2.007. Whenever I check something, whether it be through the button on the Videos Tab or by right clicking it, it's will hang at the "Waiting" stage with no indicator it's actually doing anything even after an hour.
I suspect it's failing to fetch file sizes since if I were to stop the operation, only the first video of a playlist/channel will appear in the Video Index displaying _unknown_ where it's size would be.

I have no issues downloading videos though Tartube, this is only a problem when checking.

**Comment by axcore** [comment]
Check something, wait for Tartube to hang, and then show me what you see in the **Output** tab.

**Comment by SuperScoops** [comment]
The output on the left uses a custom file name template I used when first submitting the ticket, but for the sake of it I performed another check with the default settings which is what you see on the right.
https://i.imgur.com/yQ7sA2Y.png

**Comment by axcore** [comment]
Check that the channel's URL is right. I opened this in a web browser, and YouTube says the channel doesn't exist.

`https://www.youtube.com/channel/UC2oWuUSd3t3t503Vxp4lgAA`

**Comment by axcore** [comment]
I tried the same conditions, and the check begins after just a few seconds:

![jerma](https://user-images.githubusercontent.com/37951926/96754587-6b086a80-13c9-11eb-8f65-58e5541fa4f7.png)

Check that youtube-dl is updated (**Operations > Update youtube-dl**). Check that there is nothing unexpected in the **Errors/Warnings** tab.

Try running Tartube from inside a terminal window, in case there's a python error. Enable hidden folders on your system, then run **C:\\Users\\YOURNAME\\AppData\\Local\\Tartube\\msys64\\mingw64.exe**. In the terminal window, type these commands to run Tartube, and then test your channel again:

```
cd /home/user/tartube
python3 tartube/tartube
```

**Comment by SuperScoops** [comment]
So I did that and saw this in the console.

![image](https://user-images.githubusercontent.com/12111501/96758445-82c00d00-1422-11eb-99d4-093bf8291ec6.png)

I had all of the options under **File move options** ticked, after unticking them I was able to progress further into checking the videos. Still wasn't displaying file sizes, but at least it was working though the list until it stopped again shortly later.

![image](https://user-images.githubusercontent.com/12111501/96759474-d717bc80-1423-11eb-91c2-4b9b3191de9f.png)

Afterwards I tried checking other miscellaneous videos with unicode characters in their titles and they caused the program to hang as well. Hopefully these screenshots assist in narrowing down the issues somewhat.

**Comment by axcore** [comment]
Ok, that's a one-line fix.

Open this file in a text editor: C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\tartube\utils.py

Find line 1222, which is this:

`path_list = utils.find_thumbnail_restricted(app_obj, video_obj)
`
And remove the **utils.** part:

`path_list = find_thumbnail_restricted(app_obj, video_obj)
`
Try that first, and then we'll look at your unicode problem.

**Comment by axcore** [comment]
I have a partial fix for the unicode problem, which will be in the next release. Meanwhile, you can just disable writing file names to the terminal window:

Click **Edit > System preferences... > Output > Terminal window**, and deselect **Write output from downloader's STDOUT to the terminal window**

**Comment by axcore** [comment]
The next release is available (currently from git and pypi only). It fixes both problems.

**Comment by SuperScoops** [comment]
Thanks, that fixed the issues I was having with the original playlist. Unfortunately I've run into problems with Japanese-titled videos that were previously checking and downloading well. 

Checking hangs after adding the video to the bottom of the progress list, not moving onto the next video in the queue.

<img width="1071" alt="3" src="https://user-images.githubusercontent.com/12111501/96922645-d6eaf000-14fb-11eb-8c9d-919520f5b5d8.png">

Downloading will save the video and all additional files until completion, but likewise remains in the pre-processing stage and won't advance the queue.

<img width="1071" alt="4" src="https://user-images.githubusercontent.com/12111501/96922678-dfdbc180-14fb-11eb-8b0a-9550370d5a79.png">

Deselecting **Write output from downloader's STDOUT to the terminal window** didn't solve it in this case.

**Comment by axcore** [comment]
Fixed. Replace the downloads.py file with [this one](https://github.com/axcore/tartube/blob/master/tartube/downloads.py).

**Comment by SuperScoops** [comment]
Checking now works perfectly, although after testing I'm still getting the same downloading bug.

**Comment by axcore** [comment]
Which download bug?

**Comment by SuperScoops** [comment]
The last screenshot I posted, where the file will download but get stuck in the pre-processing stage.

**Comment by axcore** [comment]
Hmmm, that's odd. The same video is downloading fine on my Windows box.

![workingfine](https://user-images.githubusercontent.com/37951926/97007475-5fd44c80-1539-11eb-8c3f-3b97deac1ad1.png)

Are you absolutely sure that you replaced the **downloads.py** file? You can test this by deleting the one you have, downloading the new one into the right folder, and then starting Tartube again.

**Comment by SuperScoops** [comment]
To clarify, I replaced `\AppData\Local\Tartube\msys64\home\user\tartube\tartube\downloads.py` with [this file](https://github.com/axcore/tartube/blob/master/downloads.py). I'm also using all of the most recent files in the repo if that would make a difference.

**Comment by axcore** [comment]
Ok, here is the problem: Tartube borrows a lot of code from [youtube-dl-gui](https://mrs0m30n3.github.io/youtube-dl-gui/). That code converts incoming data into the modern UTF-8 on most systems, but the ancient CP1251 on MS WIndows.

There are no indications in the code of why CP1251 is used, so it's difficult to know whether it's safe to remove it altogether. Also, I can't reproduce this specific error.

I have just released some more code; perhaps you can test it. If it doesn't work, we can try something else.

You would need to download all of the source code (not just `downloads.py`), replacing the existing code in the` C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube `folder.

**Comment by SuperScoops** [comment]
Did that and it still doesn't work. This is what I now see in the terminal.
![image](https://user-images.githubusercontent.com/12111501/97030934-4370f800-15ab-11eb-911d-ad7428ca6bd6.png)

**Comment by axcore** [comment]
Ok, grab the new [downloads.py](https://github.com/axcore/tartube/blob/master/tartube/downloads.py) file, copy it to the Tartube folder as before, let's see what happens.

**Comment by SuperScoops** [comment]
Happy to report that it seems to be fixed! 
At least with **Write output from downloader's STDOUT to the terminal window** disabled anyway.

![7](https://user-images.githubusercontent.com/12111501/97086749-ffe0c180-1670-11eb-891b-ca005f4d14c8.png)

With that setting enabled, this is what I see. 

![8](https://user-images.githubusercontent.com/12111501/97086674-8f39a500-1670-11eb-8feb-38c365e9d4d7.png)

Still, as far as downloading videos goes, the program is a lot more usable now than it was yesterday . Thanks for finding a solution as quickly as you have.

**Comment by axcore** [comment]
The v2.2.060 code intercepts the STDOUT error you reported in the latest screenshot. Not being a Windows programme, I'm not sure what's causing all the problems with Japanese text, but with luck you shouldn't experience any crashes now.

**Comment by axcore** [comment]
All v2.3.0 packages should contain this fix.
