### ISSUE TITLE
Unable to run tartube.py

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#2]
Unable to run tartube.py
```
$ python3 --version
Python 3.6.7
evander@evander ~/Desktop/tartube $ python3 tartube.py 
Traceback (most recent call last):
  File "tartube.py", line 32, in <module>
    from lib import mainapp
ImportError: cannot import name 'mainapp'
evander@evander ~/Desktop/tartube $ 
```
* Linux Mint 19.3 xfce
* Commit: https://github.com/axcore/tartube/commit/cdaa2ba53c31f4ca39c817c331e93dd91866c224

**Comment by axcore** [comment]
'python3 tartube.py' doesn't work for me either, but 'python tartube.py' works just fine.

Why? It's a mystery to me, too :)

**Comment by mbnoimi** [comment]
`python tartube.py` doesn't work too!

```
$ python tartube.py 
Traceback (most recent call last):
  File "tartube.py", line 32, in <module>
    from lib import mainapp
ImportError: No module named lib
$ python --version
Python 2.7.15rc1
```

**Comment by axcore** [comment]
I fixed 'python3 tartube.py', now I'm trying to fix some new issues.

**Comment by axcore** [comment]
I uploaded some new code. On a fresh install of Debian, I used the following procedure to install Tartube:

```
su
apt-get update
apt install python3-pip
exit
python3 -m pip install tartube
```

Using code downloaded directly from github, I used this command to run Tartube without installing anything:

`python3 tartube.py`

**Comment by mbnoimi** [comment]
> Using code downloaded directly from github, I used this command to run Tartube without installing anything:
> 
> `python3 tartube.py`

This time I didn't test `pip` but I run `python3 tartube.py` and the result still the same!

```
$ python3 tartube.py 
Traceback (most recent call last):
  File "tartube.py", line 32, in <module>
    from lib import mainapp
ImportError: cannot import name 'mainapp'
```
commit: https://github.com/axcore/tartube/commit/424ccecc6b8ba5a859c89a4c94caeb769e9be32c

**Comment by axcore** [comment]
Which operating system are you using?

**Comment by mbnoimi** [comment]
Linux Mint 19.3 xfce

> Which operating system are you using?

**Comment by axcore** [comment]
Hmmm... I just made a new installation of Mint xfce 19.1. I didn't install any software, just downloaded Tartube from git, extracted the zip file, changed directory, and ran 'python3 tartube.py'

![xfce](https://user-images.githubusercontent.com/37951926/58538064-3f8d4a80-81ec-11e9-8b13-1fc3a392355e.png)

**Comment by robnrene** [comment]
I get this trying to run it in Windows 7

```
# tartube.py
Traceback (most recent call last):
  File "C:\Portable Software\tartube\tartube.py", line 32, in <module>
    from lib import mainapp
  File "C:\Portable Software\tartube\lib\mainapp.py", line 24, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by axcore** [comment]
I haven't tried running anything on MS Windows yet. The link below describes how to install PyGObject, but it's not a simple install:

https://pygobject.readthedocs.io/en/latest/getting_started.html

At some point I'll create a proper installer for MS Windows, but it's pointless at the moment because of the frequent crashes.

**Comment by axcore** [comment]
The installer for MS Windows is now available. I hope it works for you!

[https://sourceforge.net/projects/tartube/](url)
