### ISSUE TITLE
Tartube crashing on startup

### ISSUE THREAD

**Issue by Hplr63** [axcore/tartube#238]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10 (Build 19042)

### What version of Tartube are you using?
Tartube 2.3.0.42

### What happens when you run Tartube from a terminal window?
This shows up:

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\Users\Marek Pl\xe1\u0161ek\AppData\Local\Tartube\msys64\mingw64\bin\python3.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:/Users/Marek Pl\xe1\u0161ek/AppData/Local/Tartube/msys64/mingw64/bin/python3.exe'
  sys.base_prefix = 'D:/msys64/mingw64'
  sys.base_exec_prefix = 'D:/msys64/mingw64'
  sys.executable = 'C:/Users/Marek Pl\xe1\u0161ek/AppData/Local/Tartube/msys64/mingw64/bin/python3.exe'
  sys.prefix = 'D:/msys64/mingw64'
  sys.exec_prefix = 'D:/msys64/mingw64'
  sys.path = [
    'D:/msys64/mingw64/lib/python38.zip',
    'D:/msys64/mingw64/lib/python3.8',
    'D:/msys64/mingw64/lib/python3.8',
    'D:/msys64/mingw64/lib/lib-dynload',
  ]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003d50 (most recent call first):
<no Python frame>
```

###If your bug report is "I can't download this video", please provide a link to the video
I can't even start Tartube at all! When I open it, a terminal opens for a few frames and then closes.

Video: https://user-images.githubusercontent.com/45365053/103425800-1d706100-4bb5-11eb-900a-9f6ed1e65958.mp4

**Comment by axcore** [comment]
Was FFmpeg installed on your system, before you installed Tartube?

**Comment by Hplr63** [comment]
no...
_aaahhh that's a dependency isn't it?_

**Comment by axcore** [comment]
Someone else mentioned crashes that were resolved by uninstalling FFmpeg, which is why I'm asking that question first.

**Comment by Hplr63** [comment]
Oh, ok. When I submitted this issue, I didn't have ffmpeg installed.
But after I submitted the issue and you replied, I installed it but it still doesn't work.

**Comment by axcore** [comment]
>Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding

I'm sorry, I don't know enough about python to say how this can be fixed.

**Comment by axcore** [comment]
Closed for inactivity. Both Tartube and FFmpeg have changed drastically since this issue was opened. If you are still having the same problem with the updated code, please open a new issue.
