### ISSUE TITLE
Folder issue

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#316]
This is an issue going back to at least 2.3.206 until today.

I created a new folder, then with it highlighted clicked add a channel but the "add this inside a folder" was empty. Clicking the folder dropdown and there is half a screen worth of blank lines at the top, then I go to find the new folder and it isn't in the list.

It is also empty if I go to add a playlist.

However, if I go to create a new folder, it shows up:

![image](https://user-images.githubusercontent.com/16659133/127803378-330113a5-271b-4b02-943d-fcceccd97ccc.png)

It also shows up in the "set download destination" window, albeit at the very top (even when a different folder in the main window is selected, in the case below TV was) and not alphabetical. On another note this prompt is only showing some of mychannels so it might be skipping over some still?

![image](https://user-images.githubusercontent.com/16659133/127803429-ad90b22f-45e7-47a3-a90f-996137d2a057.png)

Could the code for selecting the parent folder for all dialogues be extracted into a function based on the code in the "set download destination" window?

A few other folder questions that are all related:

Is it possible to display folders in the selection window based on their nested structure instead of a flat list?

Is it possible to be able to have folders with the same names (under different sections of the folder tree)?
IE for a few different folders there are some content that I just care about saving the audio, so I'd like to be able to do Music\Audio Only and Podcasts\Audio Only for example.

Since channels/playlists create a folder on the filesystem, can we choose them as the "add inside a folder" location? They currently show under the "set download destination."
IE have a channel "Game streams" and then be able to add playlists under it for "Starcraft", "HotS" etc and have them be nested underneath. 

Right now my hack for the channel/playlist issue is:
Create folder "Some Channel"
add a channel under it called "c Some Channel" (because it can't be the same name)
add playlists under "Some Channel"
set download destinations for all of them to "Some Channel"

Thanks Axcore!

**Comment by axcore** [comment]
I tested your problem on Linux and MS Windows, but I couldn't reproduce it.

Can you please test v2.3.302 (uploaded to Github and pypi). I have added a debug message so we can see what is being added to the dropdown box.

Run Tartube from a terminal window, and show me the debug message.

**Comment by axcore** [comment]
>Is it possible to display folders in the selection window based on their nested structure instead of a flat list?
Possible but I won't have time to add it before the next full release

>Is it possible to be able to have folders with the same names (under different sections of the folder tree)?
Not possible without a complete rewrite of the code, since each channel/playlist/folder is identified using its name. Don't forget that you can change the name, as it appears in the Videos Tab (for example, right-click a channel and select **Channel actions > Set nickname..**.)

>Since channels/playlists create a folder on the filesystem, can we choose them as the "add inside a folder" location? They currently show under the "set download destination."
Also not possible without a big rewrite. The code just assumes that channels/playlists don't contain anything except videos.

**Comment by ceonelson** [comment]
Created a new db, added a couple top level folders, tried to add a channel and this is all that was written:

`$ python3.8 tartube/tartube
['', 'Temporary Videos']`

Those two folders were the start of the debug output on my main database, which didn't list all of the folders in the rest of the array.

![image](https://user-images.githubusercontent.com/16659133/127933002-dc152e39-282d-4b52-adee-4f1abf5a6686.png)

It didn't put the blank lines all the way up to the top of the window though.

I've attached the db file so hopefully it shows up on your system as well!

[tartube folder issue.zip](https://github.com/axcore/tartube/files/6919955/tartube.folder.issue.zip)

Thanks Axcore!

**Comment by axcore** [comment]
I know about the missing folders. What about the first problem - the enough mostly-empty dropdown box. What do you see in the terminal window when that happens?

**Comment by axcore** [comment]
I fixed the missing folder problem in v2.3.306. There is a new installer for MS Windows, so you can try that, maybe the enormous drop-down box was a Gtk issue.

**Comment by ceonelson** [comment]
Did a clean install of the new version and that showed the folder, thanks axcore!

It is still showing the giant white area on the top half of the dropdown. The debug output is stripped in the release but I tested it before the update and got the output of `$ python3.8 tartube/tartube ['', 'Temporary Videos']` followed by most of my folder names. No GTK or other errors.

It's not that big of deal since I can now access my new folder so that's the important thing. 

Since we can't have duplicate names I don't really think that displaying the folders by nested structure rather than a flat list is worth putting any time into since most of the time I imagine people have where they want it to go highlighted before pressing the button so it will auto-fill the location... and if they don't, they should! :D

Thanks again Axcore!
