### ISSUE TITLE
Doesn't finish!

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#34]
Hi,

In case there is an error occurs during downloading process `Tartube` doesn't finish the download process even if I call `Stop`!

Ex. The following video violate copyrights so it shows an error thus `Tartube` doesn't finish:
https://www.youtube.com/watch?v=PMXYbcHzrIg
![image](https://user-images.githubusercontent.com/284547/71782222-e5a5fc00-2fe8-11ea-8009-07a285f1f19e.png)

![image](https://user-images.githubusercontent.com/284547/71782225-f191be00-2fe8-11ea-9003-741ba25c676c.png)

![Peek 2020-01-05 18-29](https://user-images.githubusercontent.com/284547/71782273-5c42f980-2fe9-11ea-810f-7503c27c8a04.gif)

* Tartube: v1.3.007
* Linux mint 19.3 xfce

**Comment by axcore** [comment]
Unfortunately I can't reproduce your problem exactly, because the video is not copyright-blocked in the UK.

I have seen this behaviour before; it is some problem with python threads. I have not found the cause yet, because it is so difficult to reproduce.

**Comment by mbnoimi** [comment]
This issue always occurs and I noticed another thing.
The progress & output tabs don't update in case Tartube captured one of this kind of the videos

**Comment by mbnoimi** [comment]
This issue is really annoying. Do you want to record a video/gif for it?

**Comment by axcore** [comment]
> This issue always occurs
I'm running Tartube 24/7, with about 500 channels and 100,000 videos downloaded so far, and for me, this issue is extremely rare. If it always occurs for you, you are very unlucky :)

>This issue is really annoying. Do you want to record a video/gif for it?
No. I am looking for a fix. I will make a release some time this week. The other things you wanted (drag and drop, tray icon, default folder) are already finished.

**Comment by mbnoimi** [comment]
OK then I'll test the new release.
BTW, I'm running Tartube 24/7 for 20 channels/playlists while the bug always occurs.
Currently Tartube useless because this bug makes Tartube GUI any without progress (I don't know which videos are downloading) thus I forced to revert back to `youtube-dl` cli interface.

**Comment by axcore** [comment]
I have spent days running tests, but I can't reproduce the problem.

Please test this issue using v1.3.042. (This release is only available here on Github).

I added a new page in the Output Tab. The new page shows information about when threads start and stop. Show me a screenshot of this page, and then we can confirm or eliminate threads as the cause of the problem.

Also, I turned on debugging mode. You can run Tartube from a terminal window:

> python3 tartube/tartube

If Tartube freezes (the Stop button doesn't work any more), you can show me a screenshot of the terminal window, and then I will know what is causing the freeze.

**Comment by mbnoimi** [comment]
> Please test this issue using v1.3.042.

Unfortunately it still occurs!

> I added a new page in the Output Tab. The new page shows information about when threads start and stop. Show me a screenshot of this page, and then we can confirm or eliminate threads as the cause of the problem.

The new doesn't show any useful info about the bug.

> Also, I turned on debugging mode.

I think I could capture the bug below:
```
$ python3 tartube >log.txt
/home/server/tartube/mainwin.py:41: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

(tartube:9967): Gdk-CRITICAL **: 17:27:37.746: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/home/server/tartube/mainapp.py", line 7533, in dl_timer_callback
    self.main_win_obj.results_list_update_row()
  File "/home/server/tartube/mainwin.py", line 5563, in results_list_update_row
    mkv_flag,
  File "/home/server/tartube/mainapp.py", line 4372, in update_video_when_file_found
    True,               # Move the file
  File "/home/server/tartube/utils.py", line 210, in convert_path_to_temp
    os.rename(old_path, new_path)
OSError: [Errno 18] Invalid cross-device link: '/home/server/Downloads/youtube-dl/downloads/Documentary/Nat Geo Abu Dhabi/التشبث بالحياة الحرب العالمية الثانية - هروب أسير عبر الغابة _ ناشونال جيوغرافيك أبوظبي.description' -> '/home/server/Downloads/youtube-dl/.temp/downloads/Documentary/Nat Geo Abu Dhabi/التشبث بالحياة الحرب العالمية الثانية - هروب أسير عبر الغابة _ ناشونال جيوغرافيك أبوظبي.description'
^CTraceback (most recent call last):
  File "/home/server/tartube/mainwin.py", line 5208, in progress_list_receive_dl_stats
    def progress_list_receive_dl_stats(self, download_item_obj, dl_stat_dict):
KeyboardInterrupt
^Z
[1]+  Stopped                 python3 tartube > log.txt
$
```
This bug almost occurs for most channels,playlist and single downloads and when it occurs:
1. I no longer able to `Stop` any download.
2. Download process stop responding (although youtube-dl thread still alive).
3. All downloaded videos titles appears `(video with no name)`.
![image](https://user-images.githubusercontent.com/284547/72620675-d14ef100-3950-11ea-9ff9-69089b4213b9.png)


`log.txt` is a huge file so I'll send the last 100 lines of it:
```
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 dld 2602 is_child_process_alive
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 1600 check_dl_is_correct_type
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2277 extract_stdout_data
2020-01-17 17:30:41 dld 2512 extract_stdout_status
2020-01-17 17:30:41 dld 723 data_callback
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
2020-01-17 17:30:41 mwn 5794 output_tab_write_stdout
2020-01-17 17:30:41 dld 2602 is_child_process_alive
2020-01-17 17:30:41 mwn 5212 progress_list_receive_dl_stats
```

**Comment by mbnoimi** [comment]
Look youtube-dl instance & Tartube thread are still running (new two files added) but the process still freezing!
![image](https://user-images.githubusercontent.com/284547/72621087-a1ecb400-3951-11ea-97e9-4ef97b67dd6d.png)

**Comment by axcore** [comment]
> The new page doesn't show any useful info about the bug.

You are probably right, but I still need to see it :)

**Comment by axcore** [comment]
@mbnoimi, I suspect it is a problem with the JSON data downloaded from YouTube.

We can test this quite easily: disable downloading JSON data.

Edit > General download options... > Other files

Deselect **Write video's metadata to an .info.json file**

**Comment by mbnoimi** [comment]
> We can test this quite easily: disable downloading JSON data.

Still occurs.

```
$ python3 tartube >log.txt
/home/server/tartube/mainwin.py:41: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

(tartube:17137): Gdk-CRITICAL **: 19:31:43.678: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/home/server/tartube/mainapp.py", line 7533, in dl_timer_callback
    self.main_win_obj.results_list_update_row()
  File "/home/server/tartube/mainwin.py", line 5563, in results_list_update_row
    mkv_flag,
  File "/home/server/tartube/mainapp.py", line 4372, in update_video_when_file_found
    True,               # Move the file
  File "/home/server/tartube/utils.py", line 210, in convert_path_to_temp
    os.rename(old_path, new_path)
OSError: [Errno 18] Invalid cross-device link: "/home/server/Downloads/youtube-dl/downloads/Documentary/MProgTV2 قناة الأفلام الوثائقية/6 things you didn't know about Winston Churchill.description" -> "/home/server/Downloads/youtube-dl/.temp/downloads/Documentary/MProgTV2 قناة الأفلام الوثائقية/6 things you didn't know about Winston Churchill.description"
^CTraceback (most recent call last):
  File "/home/server/tartube/mainwin.py", line 5208, in progress_list_receive_dl_stats
    def progress_list_receive_dl_stats(self, download_item_obj, dl_stat_dict):
KeyboardInterrupt
^Z
[1]+  Stopped                 python3 tartube > log.txt
$ 
```

**Comment by mbnoimi** [comment]
> We can test this quite easily: disable downloading JSON data.

I disabled downloading all extra files but I got a similar error
![image](https://user-images.githubusercontent.com/284547/72630786-1d576100-3964-11ea-917f-995401663b01.png)
```
$ python3 tartube >log.txt
/home/server/tartube/mainwin.py:41: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

(tartube:17697): Gdk-CRITICAL **: 19:40:52.194: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/home/server/tartube/mainapp.py", line 7533, in dl_timer_callback
    self.main_win_obj.results_list_update_row()
  File "/home/server/tartube/mainwin.py", line 5563, in results_list_update_row
    mkv_flag,
  File "/home/server/tartube/mainapp.py", line 4372, in update_video_when_file_found
    True,               # Move the file
  File "/home/server/tartube/utils.py", line 210, in convert_path_to_temp
    os.rename(old_path, new_path)
OSError: [Errno 18] Invalid cross-device link: '/home/server/Downloads/youtube-dl/downloads/Documentary/Nat Geo Abu Dhabi/سمكة التونة العنيدة - أصدقاء مقربون _ ناشونال جيوغرافيك أبوظبي.description' -> '/home/server/Downloads/youtube-dl/.temp/downloads/Documentary/Nat Geo Abu Dhabi/سمكة التونة العنيدة - أصدقاء مقربون _ ناشونال جيوغرافيك أبوظبي.description'
/home/server/tartube/mainapp.py:1644: Warning: Source ID 1053 was not found when attempting to remove it
  GObject.source_remove(self.dl_timer_id)
$ 
```

**Comment by axcore** [comment]
Ok, try this:

Open the tartube/utils.py file in a text editor, find line 210

`        os.rename(old_path, new_path)`

...and replace it with this

`        shutil.move(old_path, new_path)`

(There must be exactly 8 space characters at the beginning of the line).

I'm running a test at the moment, so I can't test this change for a few hours. But you can test it, if you want to.

**Comment by mbnoimi** [comment]
I'm pretty sure now the bug occurs because of the extra files in `Other file` tab because when I reset Tartube configurations then disabled all the extra files (as shown below) this bug disappeared
![image](https://user-images.githubusercontent.com/284547/72630786-1d576100-3964-11ea-917f-995401663b01.png)

> Open the tartube/utils.py file in a text editor, find line 210
> 
> os.rename(old_path, new_path)
> 
> ...and replace it with this
> 
> shutil.move(old_path, new_path)

I modified the file as mentioned I'm testing it now (I'll come back with result after one hour)

**Comment by mbnoimi** [comment]
> Ok, try this:
> 
> Open the tartube/utils.py file in a text editor, find line 210
> 
> ` os.rename(old_path, new_path)`
> 
> ...and replace it with this
> 
> ` shutil.move(old_path, new_path)`
> 
> (There must be exactly 8 space characters at the beginning of the line).
> 
> I'm running a test at the moment, so I can't test this change for a few hours. But you can test it, if you want to.

This modification fixed the bug.
Thanks @axcore

**Comment by axcore** [comment]
Fixed in v1.3.048.

**Comment by mbnoimi** [comment]
The bug came back once again even when I disabled all the extra files!
https://user-images.githubusercontent.com/284547/72630786-1d576100-3964-11ea-917f-995401663b01.png

**Comment by mbnoimi** [comment]
I'll revert back to v1,3,007 because this bug makes Tartube GUI useless.

**Comment by axcore** [comment]
The fix was missing from v1.3.048 for some reason. The fix is added to v1.3.053, so you can try that.

**Comment by mbnoimi** [comment]
Same bug started to occur with the recent version v2.2.117

**Comment by axcore** [comment]
Do you see any python error messages, when you run Tartube from a terminal window?

**Comment by mbnoimi** [comment]
> Do you see any python error messages, when you run Tartube from a terminal window?

```
(tartube:974097): Gdk-CRITICAL **: 22:13:23.858: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 15246, in dl_timer_callback
    self.main_win_obj.results_list_update_row()
  File "/home/hpc-laptop/.tartube/tartube/mainwin.py", line 9614, in results_list_update_row
    self.app_obj.fixed_all_folder.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
1893
2
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 9672, in create_livestream_from_download
    self.mark_video_live(video_obj, live_mode, live_data_dict)
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 12118, in mark_video_live
    self.fixed_live_folder.add_child(video_obj, no_sort_flag)
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2881, in add_child
    self.sort_children()
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 3033, in sort_children
    copy_list.sort(key=functools.cmp_to_key(self.do_sort))
  File "/home/hpc-laptop/.tartube/tartube/media.py", line 2955, in do_sort
    if obj1.live_mode > obj2.live_mode:
TypeError: '>' not supported between instances of 'int' and 'dict'
```

**Comment by mbnoimi** [comment]
BTW, `youtube-dl` processes still running and Tartube unable to control them.

**Comment by axcore** [comment]
Fixed in v2.2.176. Please test it for me.

**Comment by mbnoimi** [comment]
Still occurs:

```
(tartube:574867): Gdk-CRITICAL **: 15:11:14.465: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 16100, in dl_timer_callback
    self.main_win_obj.progress_list_display_dl_stats()
  File "/home/hpc-laptop/.tartube/tartube/mainwin.py", line 9558, in progress_list_display_dl_stats
    self.progress_list_liststore.get_iter(tree_path),
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 869, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '38'
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainwin.py", line 9558, in progress_list_display_dl_stats
    self.progress_list_liststore.get_iter(tree_path),
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 869, in get_iter
    raise ValueError("invalid tree path '%s'" % path)
ValueError: invalid tree path '38'
/home/hpc-laptop/.tartube/tartube/mainapp.py:2940: Warning: Source ID 35036 was not found when attempting to remove it
  GObject.source_remove(self.dl_timer_id)
$ 
```

**Comment by axcore** [comment]
I cannot reproduce this error, but I can guess at the cause:

In the **Progress** tab, there is a button called **Hide rows when they are finished**. Make sure it is NOT selected.

Then tell me if you see the same python error, or not.

**Comment by mbnoimi** [comment]
> In the Progress tab, there is a button called Hide rows when they are finished. Make sure it is NOT selected.

The bug disappeared after unchecking `Hide rows when they are finished`

**Comment by axcore** [comment]
Great, I can intercept that kind of error quite easily.

**Comment by axcore** [comment]
This should be fixed in v2.2.198, so you can reenable ` Hide rows when they are finished`. Let me know if you have any further problems.

**Comment by mbnoimi** [comment]
> This should be fixed in v2.2.198, so you can reenable ` Hide rows when they are finished`. Let me know if you have any further problems.

Thanks. Unable to launch v2.2.198
```
$ python3 tartube
Traceback (most recent call last):
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 2393, in do_activate
    self.start()
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 2558, in start
    new_config_flag = self.load_config()
  File "/home/hpc-laptop/.tartube/tartube/mainapp.py", line 3439, in load_config
    self.ytsc_write_verbose_flag = json_dict['ytsc_write_verbose_flag']
KeyError: 'ytsc_write_verbose_flag'
```

**Comment by axcore** [comment]
I promise, I do test things before I release them :)

Fixed.
